name: TypeScript Validation

on:
  push:
    branches: [ master, clean-rebuild ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: TypeScript Compilation Check
        run: npx tsc --noEmit
      
      - name: ESLint Check
        run: npx eslint 'src/**/*.{js,ts}' || echo "Linting issues found"